# Generated by Django 4.2 on 2023-05-23 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Тема опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('is_completed', models.ManyToManyField(blank=True, default=None, related_name='completed', to=settings.AUTH_USER_MODEL)),
                ('is_right_user_completed', models.ManyToManyField(blank=True, default=None, related_name='right_completed', to=settings.AUTH_USER_MODEL)),
                ('parent_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ответ')),
                ('is_true', models.BooleanField(default=False)),
                ('is_user_answer', models.ManyToManyField(blank=True, default=None, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
