# Generated by Django 4.2 on 2023-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_parent_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Тема опроса'),
        ),
    ]
