# Generated by Django 4.2 on 2023-06-08 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_alter_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_completed',
            field=models.ManyToManyField(related_name='quiz_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
