# Generated by Django 4.2 on 2023-06-13 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_quiz_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_completed',
            field=models.ManyToManyField(blank=True, related_name='quiz_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
