# Generated by Django 4.2 on 2023-04-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptt_blog', '0002_post_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
