# Generated by Django 4.2 on 2023-04-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptt_blog', '0005_alter_post_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
