# Generated by Django 4.2 on 2023-04-24 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mptt_blog', '0007_post_like_count_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentspost',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
