# Generated by Django 4.2 on 2023-04-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptt_blog', '0008_commentspost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentspost',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
