# Generated by Django 4.2 on 2023-08-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('invite', models.CharField(blank=True, max_length=6, null=True)),
                ('self_invite', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
