# Generated by Django 4.2 on 2023-08-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_phone_api', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
