# Generated by Django 4.2 on 2023-08-30 11:46

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ather', '0002_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Персона'),
        ),
        migrations.AlterField(
            model_name='person',
            name='text1',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текс1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='text2',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текс2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='video_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
