# Generated by Django 4.2 on 2023-09-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ather', '0003_person_date_alter_person_name_alter_person_text1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='visit_password',
            field=models.CharField(max_length=10, verbose_name='Пароль для просмотра'),
        ),
    ]
