# Generated by Django 4.2 on 2023-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_email', models.CharField(max_length=100, verbose_name='Хостинг, пример: smtp.gmail.com')),
                ('name_email', models.CharField(max_length=100, verbose_name='Имя почты, пример: testemailru014@gmail.com')),
                ('password_email', models.CharField(max_length=100, verbose_name='Пароль, пример: 1234dssads12')),
                ('port_email', models.IntegerField(verbose_name='Порт, пример: 587')),
                ('is_active', models.CharField(choices=[('True', 'Использовать почту'), ('False', 'Не использовать почту')], default='False', max_length=5, verbose_name='Статус почты')),
            ],
            options={
                'verbose_name': 'Почта',
                'verbose_name_plural': 'Почты',
            },
        ),
    ]
