# Generated by Django 4.2 on 2023-08-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_project_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniqueip',
            name='count_visit',
        ),
        migrations.AlterField(
            model_name='uniqueip',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
