# Generated by Django 4.2 on 2023-07-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_emailsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myeducation',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Слаг'),
        ),
    ]
