# Generated by Django 4.2 on 2023-08-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_uniqueip_count_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueip',
            name='date',
            field=models.DateField(),
        ),
    ]
