# Generated by Django 4.2 on 2023-07-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_uniqueip'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueip',
            name='date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
