# Generated by Django 4.2 on 2023-07-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_uniqueip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueip',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
