# Generated by Django 4.2 on 2023-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_uniqueip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueip',
            name='count_visit',
            field=models.BigIntegerField(default=0),
        ),
    ]
