# Generated by Django 4.2 on 2023-07-31 11:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_uniqueip_count_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=33, verbose_name='Заголовок ')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
