# Generated by Django 4.2 on 2023-07-31 19:01

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniqueip',
            options={'verbose_name': 'Посетитель', 'verbose_name_plural': 'Посетители '},
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
