# Generated by Django 4.2 on 2023-08-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_uniqueip_options_feedback_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueip',
            name='info_client',
            field=models.TextField(default='Нет информации'),
        ),
        migrations.AddField(
            model_name='uniqueip',
            name='path_client',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, max_length=33, verbose_name='Заголовок '),
        ),
    ]
