# Generated by Django 4.2 on 2023-08-08 07:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_uniqueip_info_client_uniqueip_path_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=3000, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='uniqueip',
            name='info_client',
            field=ckeditor.fields.RichTextField(default='Нет информации'),
        ),
    ]
